### ISSUE TITLE
Calendar and text sizes

### ISSUE THREAD

**Issue by daviddelmonte** [adventam10/AMCalendar#1]
This is my favorite calendar control. Thanks!

Is there a way to change the size of the calendar and label sizes? Thanks

**Comment by adventam10** [comment]
@daviddelmonte 

Thank you for your inquiry.

You can change the calendar size. The calendar size depends on `onView` size. Label sizes also depends on `onView` size. Unfortunately, you cannot set label sizes.

```swift
func setCalendar(onView: UIView, parentViewController: UIViewController, selectedDate: Date?, delegate: AMCalendarDelegate?) -> AMCalendar
``` 

Thank you,

**Comment by daviddelmonte** [comment]
Thanks!
